import SideNavbar from "@/components/SideNavbar/SideNavbar";
import SmallDeviceNav from "@/components/SmallDeviceNav";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="drawer lg:drawer-open">
          <input id="my-drawer-2" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content bg-[#0A192F] flex flex-col items-center justify-center">
            <div className="lg:hidden block w-full">
              <SmallDeviceNav />
            </div>
            <div className="flex justify-center items-center w-full px-0 lg:px-16 text-white">
              {children}
            </div>
          </div>
          <div className="drawer-side">
            <label
              htmlFor="my-drawer-2"
              aria-label="close sidebar"
              className="drawer-overlay"
            ></label>
            <ul className="menu bg-[#07101F] text-base-content min-h-full w-64 p-0">
              <SideNavbar></SideNavbar>
            </ul>
          </div>
        </div>
      </body>
    </html>
  );
}
