import SideNavbar from "@/components/SideNavbar/SideNavbar";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen bg-[#0A192F] gap-4 justify-between">
          <div className="w-[18%] bg-[#07101F] text-white">
            <SideNavbar></SideNavbar>
          </div>
          <div className="flex justify-center items-center w-full px-16 text-white">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
